name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write   # allow push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npx gh-pages -d dist -b gh-pages -u "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

